spring:
  profiles:
    active: test

---
spring:
  config:
    activate:
      on-profile: test
    import:
      - application-test.yml

---
spring:
  config:
    activate:
      on-profile: dev
    import:
      - application-dev.yml
      - application-security.yml

---
spring:
  config:
    activate:
      on-profile: prod
    import:
      - application-prod.yml
      - application-security.yml