# JWT
jwt:
  secret-key: ${JWT_SECRET-KEY}
  access-token-expiry-date: 300000
  refresh-token-expiry-date: 600000

# KaKao OAuth2
kakao:
  kapi-uri: https://kapi.kakao.com
  user-info-uri: /v2/user/me