spring:
  datasource:
    url: jdbc:postgresql://${SERVER_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  devtools:
    restart:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    root: DEBUG
    web: DEBUG
    org:
      springframework:
        security: DEBUG