# JWT
jwt:
  secret-key: ${JWT_SECRET-KEY}
  signup-access-token-expiry-date: 30000
  access-token-expiry-date: 30000
  refresh-token-expiry-date: 60000

# KaKao OAuth2
kakao:
  kapi-uri: https://kapi.kakao.com
  user-info-uri: /v2/user/me